### ISSUE TITLE
Setup Script Permissions Issues

### ISSUE THREAD

**Issue by jfavrod** [jfavrod/Chameleon#15]

**Comment by jfavrod** [comment]
This is the error received when the Logger is used in a fresh Chameleon setup:
(the log/chameleon.log file exists).

Fatal error: Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/usr/local/www/lessons/log/chameleon.log" could not be opened: failed to open stream: Permission denied' in /usr/local/www/lessons/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:84 Stack trace: #0 /usr/local/www/lessons/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\StreamHandler->write(Array) #1 /usr/local/www/lessons/vendor/monolog/monolog/src/Monolog/Logger.php(265): Monolog\Handler\AbstractProcessingHandler->handle(Array) #2 /usr/local/www/lessons/vendor/monolog/monolog/src/Monolog/Logger.php(329): Monolog\Logger->addRecord(400, 'Epoque\Chameleo...', Array) #3 /usr/local/www/lessons/vendor/epoque/chameleon/src/Router.php(104): Monolog\Logger->addError('Epoque\Chameleo...') #4 /usr/local/www/lessons/vendor/epoque/chameleon/src/Router.php(66): Epoque\Chameleon\Router::validRoute(Array) #5 /usr/local/www/lessons/index.php(14): Epoque\Chameleon\Router::addRoute(Array) in /usr/local/www/lessons/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 84

**Comment by jfavrod** [comment]
Setup script is now setting the permissions; commit 7afd5cff9c5c5ce43294de7cdfa83e8640ee3b3d
